commonsVersion=latest.release
commonsCompress=latest.release
springBootVersion=latest.release
nativeVersion=latest.release
springAiVersion=latest.release
tikaParser=latest.release
mime4j=latest.release
googleBom=latest.release
springCloudGcpVersion=latest.release
depVersion=latest.release
springCloudVersion=latest.release

