spring:
  application:
    name: AIAgents
  ai:
    model:
      embedding:
        text: none
    vectorstore:
      elasticsearch:
        dimensions: 1536
        initialize-schema: true
        index-name: policy-ai-index
    ollama:
      chat:
        model: gemma2
      embedding:
        model: mxbai-embed-large
    vertex:
      ai:
        gemini:
          projectId: basicdocumentai
          location: us-central1
          credentialsUri: file:/mnt/nas/CodeDataset/keys/serviceaccount.json
    azure:
      openai:
        api-key: ${AZURE_OPENAI_KEY}
        endpoint: https://basicai.openai.azure.com/
        chat:
          options:
            deployment-name: Basic-Mini
    chat:
      client:
        enabled: false
  aop:
    proxy-target-class: false
    auto: true


  elasticsearch:
    password: ElasticAdminPassword
    uris: http://192.168.1.84:30003/
    username: elastic
  codec:
    max-in-memory-size: 2GB
  threads:
    virtual:
      enabled: true
cloud:
  microsoft:
    endpoint: https://basicdocintel.cognitiveservices.azure.com/
    key: ${AZURE_KEY:none}

  google:
    cred-path: '/mnt/nas/CodeDataset/keys/serviceaccount.json'
    project-id: basicdocumentai
    location: us
    layout-processer-id: 5b561e1fd378c67a
    bucket: doaibucket

