spring:
  application:
    name: AIAgents
  ai:
    vectorstore:
      elasticsearch:
        dimensions: 1024
        initialize-schema: true
        index-name: policy-ai-index
    openai:
      base-url: http://localhost:8080
      api-key: 'not-used'
  aop:
    proxy-target-class: false
    auto: true
  elasticsearch:
    password: Admin
    uris: http://192.168.1.84:30003/
    username: elastic
  http:
    codecs:
      max-in-memory-size: 2GB
  threads:
    virtual:
      enabled: true
  data:
    #    mongodb:
    #      host: 192.168.1.84
    #      username: mongo
    #      password: Admin
    #      port: 27017

    elasticsearch:
      repositories:
        enabled: true

cloud:
  microsoft:
    endpoint: https://basicdocintel.cognitiveservices.azure.com/
    key: ${AZURE_KEY:none}

  google:
    cred-path: '/mnt/nas/CodeDataset/keys/serviceaccount.json'
    project-id: basicdocumentai
    location: us
    layout-processer-id: 5b561e1fd378c67a
    bucket: doaibucket

aws:
  access-key: ${AWS_ACCESS_KEY:your-access-key}
  secret-key: ${AWS_SECRET_KEY:your-secret-key}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET:your-bucket-name}

python:
  service:
    base-url: http://localhost:8001
    clustering-endpoint: /cluster
    classification-endpoint: http://localhost:8002

document:
  repository:
    base-path: "/mnt/nas/CodeDataset/test"